# Generated by Django 3.1.6 on 2021-04-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
