# Generated by Django 3.0 on 2021-05-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_capa',
            field=models.ImageField(default='default.jpeg', upload_to='img_perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logo',
            field=models.ImageField(default='default.jpeg', upload_to='img_perfil'),
        ),
    ]
