# Generated by Django 3.0 on 2021-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0002_auto_20210516_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
