# Generated by Django 3.0 on 2021-05-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0003_auto_20210516_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_capa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='logo',
        ),
    ]
