# Generated by Django 3.0 on 2021-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0004_auto_20210516_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
