# Generated by Django 3.0 on 2021-05-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0005_auto_20210516_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
