# Generated by Django 3.2.2 on 2021-05-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0006_remove_usuario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frete',
            old_name='peso_incial',
            new_name='peso_inicial',
        ),
    ]
