# Generated by Django 3.2.2 on 2021-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo_vapor', '0007_rename_peso_incial_frete_peso_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caminhoneiro',
            old_name='adrees',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='usuario',
            name='faz_frete',
            field=models.BooleanField(default=False),
        ),
    ]
